import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <div
          style={{
            background: "rgb(2,10,34)",
            // overflow: "hidden",
          }}
          className="relative z-[1] py-14 pb-20 md:pb-24 md:pt-14 h-full min-h-screen"
        >
          {/* <GlowBackground /> */}
          <div
            style={{
              background:
                "url('https://upastrology-com.b-cdn.net/web/images/analyser/general-offer/astro-pattern.png')",
            }}
            className="z-[-1] bg-contain opacity-5 absolute bg-repeat  w-full"
          ></div>
          <div
            style={{
              background:
                "radial-gradient(50% 50%at 50% 50%,rgb(19,36,78) 0%,rgba(0,72,255,0) 100%)",
              borderRadius: "100%",
              filter: "blur(0px)",
              flex: "0 0 auto",
              height: "1355px",
              mixBlendMode: "screen",
              overflow: "hidden",
              pointerEvents: "none",
              position: "absolute",
              right: "0px",
              top: "-650px",
              width: "97%",
              willChange: "transform",
              zIndex: 9,
            }}
          ></div>
          <div
            className={`cursor-pointer -mt-2 mx-auto mb-10 w-[140px] md:w-[160px]`}
          >
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000.3 186.38">
              <defs>
                <style>{`.clslogo-1{fill:#f7941d;}.clslogo-2{fill:#00ACE9;}`}</style>
              </defs>
              <g id="Layer_2" data-name="Layer 2">
                <g id="Layer_1-2" data-name="Layer 1">
                  <path
                    className="clslogo-1"
                    d="M108.22,62.1a15.71,15.71,0,0,1,7.59,2,14.48,14.48,0,0,1,5.8,5.76,15.52,15.52,0,0,1,2.08,7.69q0,4-23.26,50.58T75.14,178.35a14.3,14.3,0,0,1-5.7,5.71,15.68,15.68,0,0,1-15.43,0,14.24,14.24,0,0,1-5.75-5.71q-2-3.67-25.15-50.19T0,77.58a15.52,15.52,0,0,1,2.08-7.69,14.61,14.61,0,0,1,5.75-5.76,15.64,15.64,0,0,1,7.64-2,15.78,15.78,0,0,1,7.6,2,14.54,14.54,0,0,1,5.8,5.76Q30.94,73.61,61.7,137,92.75,73.62,94.83,69.89a14.55,14.55,0,0,1,5.75-5.76A15.64,15.64,0,0,1,108.22,62.1Z"
                  />
                  <path
                    className="clslogo-1"
                    d="M149.18,62.1l78.34.2q14.4.2,14.5,15,0,15.76-15.67,16h-61.6V155h61.51q15.57.09,15.57,15.66,0,15.19-15.28,15.38H149.18q-15.37,0-15.47-15V77.77Q133.8,62.4,149.18,62.1Zm23,62.38q.09-15.47,15.28-15.67h31.14q15.47.1,15.66,15.48-.28,15.46-15.66,15.47H187.57Q172.2,139.87,172.2,124.48Z"
                  />
                  <path
                    className="clslogo-1"
                    d="M269.25,62.3h46.42q62,.09,62,61.89-.09,61.6-60.35,61.8H269.25q-15.48.09-15.48-15.47V77.77Q253.77,62.4,269.25,62.3Zm15.57,31V155h31q30.75.28,30.56-31,.19-30.47-30.65-30.56Z"
                  />
                  <path
                    className="clslogo-1"
                    d="M404.6,62.39q15.47.11,15.76,15.28v93q-.19,15.38-15.57,15.67-15.48-.39-15.47-15.67V77.77Q389.22,62.4,404.6,62.39Z"
                  />
                  <path
                    className="clslogo-1"
                    d="M493.91,62.3l31.05.09q15.38.2,15.47,15.28-.1,15.67-15.57,15.57l-30.85.1q-30.86-.28-30.85,30.85,0,30.75,30.94,30.95h30.76q15.46.29,15.47,15.28,0,15.48-15.28,15.57H494.1q-61.89,0-62-61.9T493.72,62.3Z"
                  />
                  <path
                    className="clslogo-2"
                    d="M577,61.9h24.61V76h.32q19.65-14,49.12-14.05V86.52q-35.71,0-46.48,24.93a36.18,36.18,0,0,0-3,13.52V185.5H577Z"
                  />
                  <path
                    className="clslogo-2"
                    d="M678.63,28.73q8.76,0,11.83,9.72l.32,2.75q0,8.55-9.19,11.94l-2.43.21H678.1q-8.34,0-11.62-9.19l-.31-2.43v-.85q0-8.44,8.87-11.62ZM666.17,61.9h24.61V185.5H666.17Z"
                  />
                  <path
                    className="clslogo-2"
                    d="M748.46,61.9H855.78V86.52H748.46q-10,0-12.47,3.27a17,17,0,0,0-3.48,9.72q0,8.24,7.6,11.09l4.54.85h33.07q30,0,39.19,22.92a45.26,45.26,0,0,1,2.43,14.37q0,22.81-20.28,33a37.1,37.1,0,0,1-15.43,3.8H666.17V160.89H782.26q8.57,0,11.62-7.29l.85-5.18q0-12.46-15.11-12.47h-35.7q-14.05,0-26-10.77-10-10.56-10-26,0-13.93,9.72-25.88Q727.22,61.91,748.46,61.9Z"
                  />
                  <path
                    className="clslogo-2"
                    d="M837,0H861.6V74.05h.31a62.18,62.18,0,0,1,37.5-12.15q28,0,48.49,23.77,12.68,17.74,12.68,36.87v63H936V123.28q0-19-17.53-31.06a36.69,36.69,0,0,0-20.07-5.7q-17.43,0-29.69,15.74-7.08,9.51-7.07,23.45V185.5H837Z"
                  />
                  <path
                    className="clslogo-2"
                    d="M988.15,28.73q8.76,0,11.83,9.72l.32,2.75q0,8.55-9.19,11.94l-2.43.21h-1.06q-8.34,0-11.62-9.19l-.32-2.43v-.85q0-8.44,8.88-11.62ZM975.68,61.9h24.62V185.5H975.68Z"
                  />
                </g>
              </g>
            </svg>
          </div>

          <div className="w-full h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
